name: Build Genzflexy
on: [push]
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Genzflexy-App
          path: ./output/*.exe
